# name: value is dictionary in yml
name: Terraform deployment for VPC
on: [push]
jobs: 
  terraform-deployment:
  runs-on: ubuntu-latest
  # - introduces the list
  steps: # EXPORT CREDENTIALS 
    - name: Configure AWS Credentials 
      uses: aws-actions/configure-aws-credentials@v1
      with:
      # generate aws_access_key in aws iam / enter in https://github.com/{user}}/{project}/settings/secrets/actions
        aws-acess-key-id: ${{ secrets.AWS_ACCESS_KEY }}
      # generate aws_secret_access_key in aws iam / enter in https://github.com/{user}}/{project}/settings/secrets/actions
        aws-secret-key-id: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: "eu-central-1"

      - name: Clone/Checkout your repository code
        uses: actions/checkout@v2
      
      - name: Terraform setup
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan

      # - name: Terraform Apply
      #   run: terraform apply -auto-approve 

# 
# same as 
# {
#   "name": "Terraform deployment for vpc",
#   "on": ["push"]
#   "jobs": {
#     "terraform-deployment": {
#       "runs-on": "ubuntu-latest",
#       "steps": [
#         "name": "Configure AWS Credentials"
#       ]
#     }
#   }
# }